name: Preview Deployment Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  wait-for-vercel-preview:
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.get-preview-url.outputs.url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Wait for Vercel Preview
      uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
      id: wait-for-preview
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 300
        check_interval: 10
      continue-on-error: true
    
    - name: Get Preview URL
      id: get-preview-url
      run: |
        if [ -z "${{ steps.wait-for-preview.outputs.url }}" ]; then
          echo "No Vercel preview deployment found. Skipping preview tests."
          echo "url=" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "url=${{ steps.wait-for-preview.outputs.url }}" >> $GITHUB_OUTPUT
        echo "Preview URL: ${{ steps.wait-for-preview.outputs.url }}"

  test-against-branch-db:
    needs: wait-for-vercel-preview
    runs-on: ubuntu-latest
    if: needs.wait-for-vercel-preview.outputs.preview-url != ''
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Database URL
      run: |
        # Neon automatically creates branch databases for preview deployments
        # We just need to use the POSTGRES_URL and Neon handles the rest
        echo "Using Neon automatic branch database"
    
    - name: Run migrations on branch database
      run: |
        echo "Running database migrations..."
        npm run db:migrate
        echo "✅ Migrations completed (including auth tables)"
      env:
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        DATABASE_URL: ${{ secrets.POSTGRES_URL }}
    
    - name: Run integration tests against branch database
      run: npm test
      env:
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        DATABASE_URL: ${{ secrets.POSTGRES_URL }}
        TEST_BASE_URL: ${{ needs.wait-for-vercel-preview.outputs.preview-url }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        NODE_ENV: preview
        VERCEL_ENV: preview