name: Preview Deployment Tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  wait-for-vercel-preview:
    runs-on: ubuntu-latest
    outputs:
      preview-url: ${{ steps.get-preview-url.outputs.url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Wait for Vercel Preview
      uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
      id: wait-for-preview
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 300
        check_interval: 10
      continue-on-error: true
    
    - name: Get Preview URL
      id: get-preview-url
      run: |
        if [ -z "${{ steps.wait-for-preview.outputs.url }}" ]; then
          echo "No Vercel preview deployment found. Skipping preview tests."
          echo "url=" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "url=${{ steps.wait-for-preview.outputs.url }}" >> $GITHUB_OUTPUT
        echo "Preview URL: ${{ steps.wait-for-preview.outputs.url }}"

  test-against-branch-db:
    needs: wait-for-vercel-preview
    runs-on: ubuntu-latest
    if: needs.wait-for-vercel-preview.outputs.preview-url != ''
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Test Environment
      id: setup-test-env
      run: |
        echo "Setting up test environment for preview deployment"
        echo "Preview URL: ${{ needs.wait-for-vercel-preview.outputs.preview-url }}"
        
        # Since Vercel handles the Neon integration natively, we can't access the branch database URL
        # from outside the deployment. Instead, we'll run tests against the preview deployment itself
        # which has the correct database already connected.
        
        echo "Note: Tests will run against the preview deployment's API endpoints"
        echo "The preview deployment has its own isolated Neon branch database"
    
    - name: Run integration tests against preview deployment
      run: npm test
      env:
        # Tests will run against the preview deployment's API
        # The preview deployment already has its own Neon branch database
        TEST_BASE_URL: ${{ needs.wait-for-vercel-preview.outputs.preview-url }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        NODE_ENV: test
        VERCEL_ENV: preview
        # Use a test database for local operations if needed
        POSTGRES_URL: ${{ secrets.TEST_DATABASE_URL }}