name: Production Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Wait for Vercel Production Deployment
      uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
      id: wait-for-deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        max_timeout: 600
        check_interval: 10
        environment: Production
    
    - name: Run migrations on production database
      run: npm run db:migrate
      env:
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        DATABASE_URL: ${{ secrets.POSTGRES_URL }}
    
    - name: Verify migration success
      run: |
        echo "✅ Migrations completed successfully"
        echo "Production URL: ${{ steps.wait-for-deployment.outputs.url }}"