name: Vercel Preview Tests

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test-preview:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests before deployment
      run: npm run test:unit
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY || 'SG.test_key_for_ci' }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'sk-test_key_for_ci' }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL || 'test@example.com' }}
